import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
	assertAcceptanceCriteriaClosed,
	assertPhaseCompletionEvidence,
	assertSpecBodyReadyForImplement,
	countSubstantivePlanTasks,
	hasOpenAcceptanceCriteria,
	isBoilerplatePlanTaskLine,
	isSpecBodySubstantive,
	isThinOrBoilerplatePlan,
	OrchestrationGateError,
} from "../src/orchestration-gates.ts";
import type { PlanPhase } from "../src/plan.ts";

const boilerplatePlanBody = `# Implementation plan: demo

Linked spec: \`ged-a\`

Generated by \`scripts/pipeline/spec-to-plan.mjs\` (4c Plan).

## Phase 0 — Orient
- [ ] graphify query + getSpec — owner: orch
- [ ] Confirm footer terminal_skill and design_lane
- [ ] Phase complete (mark via patchPlan)
`;

describe("plan quality gates", () => {
	it("counts only non-boilerplate checkbox tasks", () => {
		assert.equal(
			countSubstantivePlanTasks({
				body: boilerplatePlanBody,
				phases: [],
			}),
			0,
		);
		assert.equal(
			countSubstantivePlanTasks({
				body: `${boilerplatePlanBody}\n- [ ] npm run x402:smoke on production origin\n`,
				phases: [],
			}),
			1,
		);
	});

	it("flags thin buildPlanFromSpec output", () => {
		assert.equal(isThinOrBoilerplatePlan({ body: boilerplatePlanBody, phases: [] }), true);
	});

	it("detects boilerplate task lines", () => {
		assert.equal(
			isBoilerplatePlanTaskLine("- [ ] graphify query + getSpec — owner: orch"),
			true,
		);
		assert.equal(
			isBoilerplatePlanTaskLine("- [ ] npm run test:pipeline-smoke"),
			false,
		);
	});
});

describe("spec body gate", () => {
	it("rejects footer-only spec body", () => {
		const body = `# Title

## Implementation status

| **Status** | Pending |
| **Review gate** | passed |
`;
		assert.equal(isSpecBodySubstantive(body), false);
		assert.throws(
			() => assertSpecBodyReadyForImplement({ slug: "ged-a", body }),
			OrchestrationGateError,
		);
	});

	it("accepts substantive spec body", () => {
		const body = `# Title

## Goal

Ship x402 worker with paid inference routes and discovery on production origin.

## Implementation status

| **Status** | Pending |
`;
		assert.equal(isSpecBodySubstantive(body), true);
	});
});

describe("acceptance criteria gate", () => {
	it("detects open acceptance checkboxes", () => {
		const body = `## Acceptance criteria

- [ ] live smoke passes
- [x] docs updated
`;
		assert.equal(hasOpenAcceptanceCriteria(body), true);
		assert.throws(
			() => assertAcceptanceCriteriaClosed({ slug: "ged-a", body }),
			(err: unknown) =>
				err instanceof OrchestrationGateError && err.code === "acceptance_criteria_open",
		);
	});

	it("allows ship when acceptance criteria closed", () => {
		const body = `## Acceptance criteria

- [x] live smoke passes
`;
		assert.equal(hasOpenAcceptanceCriteria(body), false);
		assert.doesNotThrow(() => assertAcceptanceCriteriaClosed({ slug: "ged-a", body }));
	});
});

describe("phase evidence gate", () => {
	const implementPhase: PlanPhase = {
		id: "p1",
		index: 1,
		title: "Deploy worker",
		status: "active",
		body: "- [ ] npm run cf:deploy",
		lock: null,
	};

	it("requires gate_command and stdout_hash for implement phases", () => {
		assert.throws(
			() => assertPhaseCompletionEvidence(implementPhase),
			(err: unknown) =>
				err instanceof OrchestrationGateError && err.code === "phase_gate_evidence_required",
		);
		assert.doesNotThrow(() =>
			assertPhaseCompletionEvidence(implementPhase, {
				gate_command: "npm run x402:smoke",
				stdout_hash: "abc123deadbeef",
			}),
		);
	});

	it("requires evidence path for research phases", () => {
		const research: PlanPhase = {
			...implementPhase,
			title: "Root-cause audit",
			body: "- [ ] inventory endpoints",
		};
		assert.throws(
			() => assertPhaseCompletionEvidence(research),
			(err: unknown) =>
				err instanceof OrchestrationGateError && err.code === "phase_evidence_required",
		);
		assert.doesNotThrow(() =>
			assertPhaseCompletionEvidence(research, { evidence: "scratch/audit.md" }),
		);
	});
});
