import type { MatrixManifest } from "./service-registry";

export const SCRIBE_MATRIX_MANIFEST: MatrixManifest = {
	id: "scribe",
	binding: "SCRIBE",
	title: "scribe",
	description: "Edge store for design specs, phased plans, and org errors.",
	version: "0.2.0",
	routes: [
		{ method: "GET", path: "/health", summary: "Worker health" },
		{ method: "GET", path: "/", summary: "Planning dashboard" },
		{ method: "GET", path: "/v1/projects/:project/specs", summary: "List active specs" },
		{ method: "GET", path: "/v1/projects/:project/specs/:slug", summary: "Read one spec" },
		{ method: "GET", path: "/v1/projects/:project/specs/:slug/revisions", summary: "List spec body revisions" },
		{ method: "GET", path: "/v1/projects/:project/specs/:slug/revisions/:baseEtag", summary: "Read one spec revision snapshot" },
		{ method: "GET", path: "/v1/projects/:project/specs/:slug/diff", summary: "Diff spec bodies by etag" },
		{ method: "POST", path: "/v1/projects/:project/specs", summary: "Save design spec" },
		{ method: "PATCH", path: "/v1/projects/:project/specs/:slug", summary: "Update status or phases" },
		{ method: "POST", path: "/v1/projects/:project/specs/:slug/lock", summary: "Acquire agent lock" },
		{ method: "DELETE", path: "/v1/projects/:project/specs/:slug/lock", summary: "Release agent lock" },
		{ method: "GET", path: "/v1/projects/:project/plans/:id", summary: "Read one plan" },
		{ method: "GET", path: "/v1/projects/:project/plans/:id/revisions", summary: "List plan body revisions" },
		{ method: "GET", path: "/v1/projects/:project/plans/:id/revisions/:baseEtag", summary: "Read one plan revision snapshot" },
		{ method: "GET", path: "/v1/projects/:project/plans/:id/diff", summary: "Plan body diff (base etag vs head)" },
		{ method: "POST", path: "/v1/projects/:project/plans", summary: "Save implementation plan" },
		{ method: "PATCH", path: "/v1/projects/:project/plans/:id", summary: "Update plan status or tasks" },
		{ method: "POST", path: "/v1/projects/:project/plans/:id/lock", summary: "Acquire plan lock" },
		{ method: "DELETE", path: "/v1/projects/:project/plans/:id/lock", summary: "Release plan lock" },
		{ method: "POST", path: "/v1/projects/:project/plans/:id/phases/:phaseId/lock", summary: "Acquire plan phase lock" },
		{ method: "DELETE", path: "/v1/projects/:project/plans/:id/phases/:phaseId/lock", summary: "Release plan phase lock" },
		{ method: "POST", path: "/v1/projects/:project/queue/take", summary: "Pick + lock closest phase or spec" },
		{ method: "GET", path: "/v1/projects/:project/plans", summary: "List plans" },
		{ method: "GET", path: "/v1/projects/:project/errors", summary: "Unresolved errors board" },
		{ method: "POST", path: "/v1/projects/:project/errors", summary: "Report error" },
		{ method: "PATCH", path: "/v1/projects/:project/errors/:id", summary: "Resolve error" },
		{ method: "GET", path: "/v1/projects/:project/services", summary: "Service registry (matrix project)" },
		{ method: "POST", path: "/v1/projects/:project/services", summary: "Upsert service registry entry" },
	],
};
